version: "2.2"
services:
    Candidate:
      container_name: candidat-service
      build: ./candidat-service
      ports:
        - "8045:8045"
      hostname: candidate
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      image: "candidate-service" 
      depends_on: 
        - Eureka

    Auth:
      container_name: auth-service
      build: ./auth-service
      ports:
        - "8081:8081"
      hostname: authentification
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      image: "auth-service"
      depends_on:
        - Eureka

    Gateway:
      container_name: api-gateway
      build: ./api-gateway
      ports:
        - "8054:8054"
      hostname: api-gateway
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      image: "api-gateway"
      depends_on:
        - Eureka


    Eureka:
      container_name: eureka-server
      build: ./eureka-server
      ports:
        - "8761:8761"
      hostname: eureka-server
      image: "eureka-server"
      environment:   
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/